stream.properties = {
  resample.quality      = 14
  channelmix.normalize  = false
  channelmix.upmix      = true
  channelmix.upmix-method = psd  # none, simple
  dither.method = none  # none, shaped5, wannamaker3, triangular-hf
}
