pulse.properties = {
    server.address = [ "unix:native" ]
    pulse.min.req          = 256/48000     # 2.7ms
    pulse.default.tlength  = 96000/48000   # 2 seconds
    pulse.min.quantum      = 256/48000     # 2.7ms
    pulse.default.format   = F32           # F32, S16
}
