# Client config file for PipeWire version "1.6.4" #

context.spa-libs = {
  audio.convert.* = audioconvert/libspa-audioconvert
  support.*       = support/libspa-support
  video.convert.* = videoconvert/libspa-videoconvert
}

context.modules = [
  { 
    name = libpipewire-module-rt
    args = { rt.prio = 88 }
    flags = [ ifexists nofail ]
    condition = [ { module.rt = !false } ]
  }
  { name = libpipewire-module-protocol-native }
  { 
    name = libpipewire-module-client-node
    condition = [ { module.client-node = !false } ]
  }
  { 
    name = libpipewire-module-client-device
    condition = [ { module.client-device = !false } ]
  }
  { 
    name = libpipewire-module-adapter
    condition = [ { module.adapter = !false } ]
  }
  { 
    name = libpipewire-module-metadata
    condition = [ { module.metadata = !false } ]
  }
  { 
    name = libpipewire-module-session-manager
    condition = [ { module.session-manager = !false } ]
  }
]

stream.properties = {
  resample.quality      = 14
  channelmix.normalize  = false
  channelmix.upmix      = true
  channelmix.upmix-method = psd  # none, simple
  dither.method = none  # none, shaped5, wannamaker3, triangular-hf
}

alsa.properties = {
  alsa.format = [ F32 S32 S24 S16 ]
  alsa.rate = { min=44100 max=384000 }
  alsa.volume-method = cubic
}

alsa.rules = [
  { matches = [ { application.process.binary = "resolve" } ]
    actions = {
      update-props = {
		    alsa.buffer-bytes = 131072
      }
    }
  }
]
