# JACK client config file for PipeWire version "1.6.4" #

context.spa-libs = {
    support.* = support/libspa-support
}

context.modules = [
  { name = libpipewire-module-rt
    args = { rt.prio = 88 }
    flags = [ ifexists nofail ]
  }
  { name = libpipewire-module-protocol-native }
  { name = libpipewire-module-client-node }
  { name = libpipewire-module-metadata }
]

jack.properties = {
    node.lock-quantum  = true
    jack.locked-process    = true
    jack.fix-midi-events   = true
    jack.global-buffer-size = true
}

jack.rules = [
    {   matches = [ { application.process.binary = "jack_bufsize" } ]
        actions = {
            update-props = {
                jack.global-buffer-size = true   # quantum set globally using metadata
            }
        }
    }
    {   matches = [ { application.process.binary = "qsynth" } ]
        actions = {
            update-props = {
                node.always-process = false # makes qsynth idle
                node.pause-on-idle = false  # makes audio fade out when idle
                node.passive = out          # makes the sink and qsynth suspend
            }
        }
    }
    {   matches = [ { client.name = "Mixxx" } ]
        actions = {
            update-props = {
                jack.merge-monitor = false
            }
        }
    }
]
