#############
### INPUT ###
#############


input {
    kb_layout = us
    follow_mouse = 1
 
    scroll_method = on_button_down
    scroll_button = 274
 
    sensitivity = 0 

    accel_profile = flat
}

cursor {
    no_hardware_cursors = false
    inactive_timeout = 10
    no_warps = true
}

