#############
### INPUT ###
#############


input {
    kb_layout = us
    follow_mouse = 1
 
    scroll_method = on_button_down
    scroll_button = 274
 
    sensitivity = 0

    accel_profile = flat

    repeat_rate = 25
    repeat_delay = 300
}

cursor {
    no_hardware_cursors = 2
    use_cpu_buffer = 0

    sync_gsettings_theme = true
    enable_hyprcursor = true

    no_warps = true
    inactive_timeout = 10
    hide_on_key_press = true

    no_break_fs_vrr = 2
    min_refresh_rate = 60
}

