############
### MISC ###
############


misc {
    vfr = true
    vrr = 0

    force_default_wallpaper = 0
    disable_hyprland_logo = true

    animate_manual_resizes = true
    focus_on_activate = false
    mouse_move_enables_dpms = false
}

render {
    direct_scanout = true
    new_render_scheduling = true
    commit_timing_enabled = true

    cm_enabled = true
    cm_auto_hdr = 1
}
