-- ###################################################################
-- ###  AUTOGENERATED HYPRLAND LUA CONFIG.                         ###
-- ###   EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.      ###
-- ###################################################################

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/hypr/?.lua"

----------------
--- MONITORS ---
----------------
require("hyprlua.monitors")


----------------------
--- WORKSPACE RULE ---
----------------------
require("hyprlua.workspace")


-----------------
--- AUTOSTART ---
-----------------
require("hyprlua.autostart")


-----------------------------
--- ENVIRONMENT VARIABLES ---
-----------------------------
require("hyprlua.environment")


---------------------
--- LOOK AND FEEL ---
---------------------
require("hyprlua.appearance")
require("hyprlua.animations")
require("hyprlua.layout")
require("hyprlua.misc")


-------------
--- INPUT ---
-------------
require("hyprlua.input")


-------------------
--- KEYBINDINGS ---
-------------------
require("hyprlua.keybindings")


--------------------
--- WINDOWS RULE ---
--------------------
require("hyprlua.windowrule")
